name: Setup Trivy Indirectly (skip-setup fix)

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      ## NB - Each call to trivy-action, which is a composite action, calls their setup-trivy action which will install 
      ##      trivy each time UNLESS we set skip-setup: true on subsequent calls

      - name: Trivy Cache
        id: trivy-cache
        uses: yogeshlonkar/trivy-cache-action@v0.1.8
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          prefix: ${{ github.workflow }}

      - name: Download TrivyDB
        uses: rvesse/trivy-action@skip-setup
        env:
          TRIVY_DOWNLOAD_DB_ONLY: true
          TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db
        with:
          scan-type: image
          cache-dir: .trivy

      - name: Trivy Vulnerability Scan
        uses: rvesse/trivy-action@skip-setup
        with:
          scan-type: "fs"
          output: trivy-report.json
          format: json
          scan-ref: .
          exit-code: 0
          cache-dir: .trivy
          skip-setup: true

      - name: Upload Vulnerability Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.json
          retention-days: 30

      - name: Fail build on High/Criticial Vulnerabilities
        uses: rvesse/trivy-action@skip-setup
        with:
          scan-type: "fs"
          format: table
          scan-ref: .
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 1
          cache-dir: .trivy
          skip-setup: true

          